name: Security Audit

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
    branches:
      - main
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}